name: Semgrep CE

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep/semgrep
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@v6

      - name: Run Semgrep CE
        run: semgrep scan --config auto --config p/typescript --config p/javascript --error
